# fly.toml app configuration file generated for actual-server-fork on 2025-01-20T21:03:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fiwell-production'
primary_region = 'gru'

[experimental]
  cmd = ['node', '--max-old-space-size=180', 'app.js']
  auto_rollback = true

[env]
  PORT = '5006'
  TINI_SUBREAPER = '1'

[[mounts]]
  source = 'actual_data'
  destination = '/data'

[http_service]
  internal_port = 5006
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 5006
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'

[[vm]]
  size = 'shared-cpu-1x'
